[theme]
primaryColor = "#2E7D6B"
backgroundColor = "#1d1d1b"
secondaryBackgroundColor = "#3a3d3c"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
